### PR TITLE
Fix `isPrintable` function for comment nodes

### LINKED ISSUE #1437: Media queries with only CSS comment as content aren't included in the output
Input:
```scss
div {

  @media screen and (min-width: 37.5em) {
    /* asd */
  }

  @media screen and (min-width: 48em) {
    display: none;
  }
}
```

Expected result ([demo with Sass 3.4.14](http://sassmeister.com/gist/6eaab83c02af289936f1))
```css
@media screen and (min-width: 37.5em) {
  div {
    /* asd */
  }
}
@media screen and (min-width: 48em) {
  div {
    display: none;
  }
}
```

Actual result ([demo with libsass 3.2.5](http://sassmeister.com/gist/38efd1df8d16cfa4392a))
```css
div {
  /* asd */
}

@media screen and (min-width: 48em) {
  div {
    display: none;
  }
}
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25669957-media-queries-with-only-css-comment-as-content-aren-t-included-in-the-output?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mgreter**
Fixes #1437

### CODE REVIEW

File: src/ast.cpp [hunk 1]
```diff
@@ -1252,6 +1252,20 @@ namespace Sass {
     }
   }
 
+  bool Ruleset::is_invisible() const {
```
Comment (xzyfer) [inline src/ast.cpp]: Good to see this logic slowly moving into `ast.cpp` :+1:

**Comment by xzyfer** [comment]
:+1:
