### PR TITLE
Fix another null pointer access

### LINKED ISSUE #2321: SIGSEGV on invalid if function call
Originally reported by @mrtuxracer
```sass
a {
  b: if(a,b,c...);
}
```
Ruby Sass
```css
a {
  b: b; }
```
LibSass
```
[1]    33262 segmentation fault
```
Spec https://github.com/sass/sass-spec/pull/1080

### PR DESCRIPTION
**Pull request by mgreter**
Hotfix 
Fixes #2321
Spec sass/sass-spec#1081

### CODE REVIEW

File: src/bind.cpp [hunk 1]
```diff
@@ -167,8 +167,15 @@ namespace Sass {
...
+            arglist->append(arg);
+          }
+        }
+
         // empty rest arg - treat all args as default values
-        if (!arglist->length()) {
+        if (!arglist || !arglist->length()) {
           break;
         } else {
           if (arglist->length() > LP - ip && !ps->has_rest_parameter()) {
```
Comment (nschonni) [inline src/bind.cpp]: This would have the same issue wouldn't it?

Comment (nschonni) [inline src/bind.cpp]: Nevermind, read it wrong
