### PR TITLE
Error when declarations are printed without ruleset

### LINKED ISSUE #1732: Including a `@mixin` when outside of selector still outputs properties
As mentioned in https://github.com/ezekg/flint/issues/40#issuecomment-156465316 and similar to https://github.com/sass/libsass/issues/1585.

### Reproducable test case:
```scss
@mixin a {
  b: c;
}

@include a();
```

### Compiling with Ruby Sass results in:

```
Error: Properties are only allowed within rules, directives, mixin includes, or other properties.
```

Cmd: `sass test.scss` 

### Compiling with Libsass results in:

```css
b: c;
```

Cmd: `sassc test.scss` 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28230251-including-a-mixin-when-outside-of-selector-still-outputs-properties?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by xzyfer**
This is introduces a vastly reduced `CheckNesting` visitor from Ruby
Sass as discussed in #2061. Doing this properly will require some
small changes to the parser, and probably eval, which currently try
to do some nesting checking of their own.

This is just first step to properly introducing the proper nesting
checking.

Spec sass/sass-spec#857
Closes #2061
Fixes #1732

### CODE REVIEW

File: src/check_nesting.cpp [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+    Block* bb = SASS_MEMORY_NEW(ctx.mem, Block, b->pstate(), b->length(), b->is_root());
+    block_stack.push_back(bb);
+    append_block(b);
+    block_stack.pop_back();
+    return bb;
+  }
+
+  Statement* CheckNesting::operator()(Declaration* d)
+  {
+    if (block_stack.size() < 2) {
```
Comment (xzyfer) [inline src/check_nesting.cpp]: This check [still needs work](https://github.com/sass/sass/blob/63586f1e51c0aec47a7afcc8cd17aa03f32f0a29/lib/sass/tree/visitors/check_nesting.rb#L140-L141) and the test case will need to be updated.

File: src/check_nesting.cpp [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+namespace Sass {
+
+  CheckNesting::CheckNesting(Context& ctx)
+  : ctx(ctx),
+    block_stack(std::vector<Block*>())
+  { }
+
+  Statement* CheckNesting::operator()(Block* b)
+  {
+    Block* bb = SASS_MEMORY_NEW(ctx.mem, Block, b->pstate(), b->length(), b->is_root());
```
Comment (mgreter) [inline src/check_nesting.cpp]: Is it really necessary to make another copy? I figure this should not be needed since we do not really alter anything here? Creating too many clones is the main reason why libsass is slower than it could be (I already removed some cloning in eval some time ago, which lead to the big performance gain). The other reason we are slower than needed is that we visit too many visitors, but I guess there is not much too avoid that ...

**Comment by mgreter** [comment]
Other than my comments, LGTM!

**Comment by xzyfer** [comment]
Beefed out the specs in https://github.com/sass/sass-spec/pull/857

File: src/check_nesting.cpp (hunk 2 above)
Comment (xzyfer) [inline src/check_nesting.cpp]: No we don't need the copy. I slimmed this down a lot, fixed the check, and beefed out the spec. This visitor should never mutate the nodes.

Comment (mgreter) [inline src/check_nesting.cpp]: IMHO if it should never mutate than the `append_block` is also superflous. Doesn't it always replace the children with itself anyway under that condition? Otherwise good work!

Comment (xzyfer) [inline src/check_nesting.cpp]: Yep I've also removed that locally. Just pushed my latest. Tracking down an error mismatch atm.

Comment (mgreter) [inline src/check_nesting.cpp]: :+1:
